version: "3.10"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID: # Your API HASH from my.telegram.org
      API_HASH: # Your API ID from my.telegram.org
      BOT_TOKEN: # Bot token, get it from @BotFather 
      ADMINS: #ADMINS
      CHANNELS: #CHANNELS
      AUTH_CHANNEL: #AUTH_CHANNEL
      AUTH_USERS: #AUTH_USERS
      DATABASE_URI: #DATABASE_URI
      LOG_CHANNEL: #LOG_CHANNEL
